# Generated by Django 3.2.10 on 2021-12-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.CharField(max_length=20)),
                ('EmpName', models.CharField(max_length=100)),
                ('EmpContact', models.CharField(max_length=20)),
                ('EmpSal', models.IntegerField()),
                ('EmpEmail', models.EmailField(max_length=254)),
                ('EmpAddress', models.TextField()),
            ],
        ),
    ]
