# Generated by Django 3.2.10 on 2021-12-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpAddress',
            field=models.TextField(max_length=500),
        ),
    ]
